backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections: # A list of collections the CMS should be able to edit
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
      - label: "Boarding School Page"
        name: "boardingschools"
        file: "content/boardingschools.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
